name: GreenHouseWF

on: 
  push:
    branches:
      - Dev
  workflow_dispatch:

env:
  HOST: greenhouse.kentcs.org
  USER: greenhouse
  TARGET: greenhouse@greenhouse.kentcs.org
  RUN: ssh -o LogLevel=ERROR -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no greenhouse@greenhouse.kentcs.org
  COPY: scp -o LogLevel=ERROR -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no

jobs:
  example_workflow:
    runs-on: ubuntu-latest
    steps:

      - name: Get our files
        uses: actions/checkout@v4

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.ID_ED25519 }}
          name: id_ed25519
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Prepare and Zip Project
        run: |
          zip -r greenhouse.zip . 

      - name: Clean up old project on Cassini
        run: |
          $RUN "rm -rf ~/web/frontend ~/web/backend ~/web/hardware ~/web/docs ~/web/tests"
          $RUN "rm -f ~/web/greenhouse.zip"

      - name: Copy and Unzip to Cassini
        run: |
          $COPY greenhouse.zip $TARGET:./web
          $RUN "cd ~/web && python3 -m zipfile -e greenhouse.zip ."

      - name: Restart Website
        run: |
          echo "Shutting down old Streamlit process..."
          $RUN "pkill -f Home.py || true"
          
          echo "Starting Streamlit Frontend (Port 15125)..."
          $RUN "cd ~/web/frontend/streamlit_app && source ~/web/venv/bin/activate && nohup streamlit run Home.py --server.port 15125 --server.address 0.0.0.0 > web.log 2>&1 &"
          
          echo "Deployment complete......."