name: GreenHouseWF

on: 
  push:
    branches:
      - Dev
  workflow_dispatch:

env:
  HOST: greenhouse.cortana.org
  USER: greenhouse
  TARGET: greenhouse@greenhouse.cortana.org
  RUN: ssh -o LogLevel=ERROR -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no greenhouse@greenhouse.cortana.org
  COPY: scp -o LogLevel=ERROR -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no

jobs:
  example_workflow:
    runs-on: ubuntu-latest
    steps:

      - name: Get our files
        uses: actions/checkout@v4

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.ID_ED25519 }}
          name: id_ed25519
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Check out the VM
        run: |
          echo $ ls -la
          ls -la
          echo $ whoami
          whoami 

      - name: Check out to greenhouse
        run: |
          echo $RUN ls -la
          $RUN ls -la

          echo $ ssh greenhouse@greenhouse.cortana.org ls -la
          ssh greenhouse@greenhouse.cortana.org ls -la 
          echo $ ssh greenhouse@greenhouse.cortana.org whoami
          ssh greenhouse@greenhouse.cortana.org whoami 
          echo $ ssh greenhouse@greenhouse.cortana.org hostname
          ssh greenhouse@greenhouse.cortana.org hostname
          echo $ greenhouse@greenhouse.cortana.org mkdir -p ./web
          ssh greenhouse@greenhouse.cortana.org mkdir -p ./web

          echo " Zipping project locally "
          zip -r greenhouse.zip . 
          ls -lh greenhouse.zip

          echo "Clean up old project on Cassini"
          $RUN "rm -rf ~/web/GREENHOUSE-MONITORING-SYSTEM"
          $RUN "rm -f ~/web/greenhouse.zip"

          echo " Copying zip to Cassini "
          echo $COPY greenhouse.zip greenhouse@greenhouse.cortana.org:./web
          $COPY greenhouse.zip greenhouse@greenhouse.cortana.org:./web

          echo " Unzipping on Cassini "
          $RUN "cd ~/web && python3 -m zipfile -e greenhouse.zip ."

          echo " Move extracted folder into place (if needed)"
          $RUN "cd ~/web && if [ -d './GREENHOUSE-MONITORING-SYSTEM-main' ]; then mv GREENHOUSE-MONITORING-SYSTEM-main GREENHOUSE-MONITORING-SYSTEM; fi"