name: GreenHouseWF

on: 
  push:
    branches:
      - Dev
  workflow_dispatch:

env:
  HOST: greenhouse.kentcs.org
  USER: greenhouse
  TARGET: greenhouse@greenhouse.kentcs.org
  RUN: ssh -o LogLevel=ERROR -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no greenhouse@greenhouse.kentcs.org
  COPY: scp -o LogLevel=ERROR -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no

jobs:
  example_workflow:
    runs-on: ubuntu-latest
    steps:

      - name: Get our files
        uses: actions/checkout@v4

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.ID_ED25519 }}
          name: id_ed25519
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Check out the VM
        run: |
          echo "$ ls -la"
          ls -la
          echo "$ whoami"
          whoami 

      - name: Check out to greenhouse
        run: |
          echo "$RUN ls -la"
          $RUN ls -la

          echo "$RUN whoami"
          $RUN whoami 

          echo "$RUN hostname"
          $RUN hostname

          echo "$RUN mkdir -p ./web"
          $RUN mkdir -p ./web

          echo " Zipping project locally "
          zip -r greenhouse.zip . 
          ls -lh greenhouse.zip

          echo "Clean up old project on Cassini"
          $RUN "rm -rf ~/web/frontend ~/web/backend ~/web/hardware ~/web/docs ~/web/tests"
          $RUN "rm -f ~/web/greenhouse.zip"

          echo " Copying zip to Cassini "
          echo "$COPY greenhouse.zip $TARGET:./web"
          $COPY greenhouse.zip $TARGET:./web

          echo " Unzipping on Cassini "
          $RUN "cd ~/web && python3 -m zipfile -e greenhouse.zip ."